blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/atomic/.github/blob/main/SECURITY.md
    about: Please read our security policy for reporting.

